# Generated by Django 4.2 on 2023-04-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.BinaryField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrátor'), ('PROJECT_MANAGER', 'Projektový manažer'), ('USER', 'Běžný uživatel')], max_length=64)),
            ],
        ),
    ]
