# Generated by Django 4.2 on 2023-04-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_riskcategory_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskcategory',
            options={'verbose_name_plural': 'Risk Categories'},
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='riskcategory',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='riskcategory',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrátor'), ('PROJECT_MANAGER', 'Projektový manažer'), ('USER', 'Běžný uživatel')], default='USER', max_length=64),
        ),
    ]
