# Generated by Django 4.2 on 2023-04-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_riskcategory_options_project_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date_begin',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='date_end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='riskcategory',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
