# Generated by Django 4.2 on 2023-04-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_riskcategory_options_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='riskcategory',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
