# Generated by Django 4.2 on 2023-04-15 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_project_date_begin_project_date_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_begin',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
