# Generated by Django 4.2 on 2023-04-15 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_userproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=512)),
                ('danger', models.CharField(max_length=512)),
                ('trigger', models.CharField(max_length=512)),
                ('reactions', models.CharField(max_length=512)),
                ('probability', models.CharField(choices=[('TINY', 'Nepatrná'), ('LOW', 'Malá'), ('MEDIUM', 'Stredná'), ('HIGH', 'Veľká'), ('EXTREME', 'Mimoriadne veľká')], max_length=64)),
                ('impact', models.CharField(choices=[('TINY', 'Nepatrný'), ('LOW', 'Malý'), ('MEDIUM', 'Cítiteľný'), ('HIGH', 'Kritický'), ('EXTREME', 'Katastrofický')], max_length=64)),
                ('status', models.CharField(choices=[('CONCEPT', 'Koncept'), ('ACTIVE', 'Aktívne'), ('CLOSED', 'Uzatvorené'), ('DELETED', 'Zmazané'), ('TRANSPIRED', 'Prihodilo sa')], max_length=64)),
                ('date_identified', models.DateField(null=True)),
                ('date_updated', models.DateField(null=True)),
                ('date_reaction', models.DateField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.riskcategory')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.project')),
            ],
        ),
    ]
