# Generated by Django 4.2 on 2023-04-15 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_risk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_begin',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='risk',
            name='description',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
