# Generated by Django 4.2 on 2023-04-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_project_date_begin_alter_risk_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('CONCEPT', 'Koncept'), ('ACTIVE', 'Aktívne'), ('CLOSED', 'Uzatvorené'), ('DELETED', 'Zmazané'), ('TRANSPIRED', 'Prihodilo sa')], default='CONCEPT', max_length=64),
        ),
    ]
